### ISSUE TITLE
Spacing issue

### ISSUE THREAD

**Issue by Vitorvlv** [jellyfin/jellyfin.github.io#20]
In the "What is Jellyfin?" section all the text are too close to each other. 

![spacing issue](https://user-images.githubusercontent.com/26132870/65192234-c3459e00-da4c-11e9-8c02-a63a4bcd8401.png)

**Comment by joshuaboniface** [comment]
Interesting, I'd never noticed that before, but mine is doing it too. Should be a quick tweak.
