### ISSUE TITLE
Fix spacing issue between screenshots

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin.github.io#23]
Looks like I messed this up in #8. The screenshots don't have enough horizontal space to show up, and this is introducing scrollbars in at least Chrome (I didn't see these in Safari when working on it).

**Comment by shawnofthedev** [comment]
I can take this one but I don't have anything with Safari to test against.

**Comment by anthonylavado** [comment]
That's no problem, I can review it :-)

**Comment by cewert** [comment]
I also worked on this and submitted a PR. I didn't see that shawnofthedev said he was going to get this one, sorry.

No hard feelings if my code doesn't get used :)

**Comment by anthonylavado** [comment]
I'll look at both, don't worry. They're both valid in my eyes 👍

**Comment by shawnofthedev** [comment]
I also will have no hard feelings as you should choose the one that fits best 👌

**Comment by anthonylavado** [comment]
fixed in #27
