### ISSUE TITLE
Convert Website to Hugo

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin.github.io#28]
The theme for this website is called Evie. Someone had made a Hugo port, but it was incomplete.

Recently, one of our main jellyfin-web contributors (@dkanada), helped fix this port up to be usable, but we need help to implement it.

The repo is available here: https://github.com/dkanada/evie-hugo

Any PRs that can help with this goal will be gladly accepted.

In the final website, we're looking to do the following:
- [ ] Keep the same styling we're using now (fonts, colours, etc.)
- [ ] Keep the same static pages that we currently have (If we need to re-write them in MD, that's fine, we just need that template)
- [ ] Create a blog section for us to start writing posts
- [ ] Bonus - Add a section that shows the most recent post title on the main page

**Comment by cewert** [comment]
Using hugo seems to break the documentation(docs folder). I just tried moving the docs folder into the content folder and index.html worked but all of the sub folders threw a 404.

I'm new to hugo so maybe I'm missing something. I'll look into this more when I get time.

**Comment by dkanada** [comment]
@cewert good news, we just modified the hosting so we can separate the docs from the main website when we migrate to hugo, so you no longer need to worry about that.

**Comment by dkanada** [comment]
@cewert @anthonylavado we might want to use the commit history for the new code rather than throw it all in the current tree, which do you guys think is better? I have no opinion, just thought it might be worth considering.

**Comment by anthonylavado** [comment]
Closed through several other PRs and new build process. Thank you to @dkanada and @cewert for making it possible 🙂
