### ISSUE TITLE
https link https://jellyfin.media redirects to non-https http://jellyfin.org

### ISSUE THREAD

**Issue by iotku** [jellyfin/jellyfin.github.io#33]
Many of the links to Jellyfin (including the main link @ https://github.com/jellyfin) are to https://jellyfin.media which redirects to http://jellyfin.org rather than https://jellyfin.org

It's a bit jarring to load something with an https prefix and get redirected to a http site.

Additionally, even though the download links are still to https repos, the pages they're being served on are plain http which could be potentially vulnerable to man-in-the-middle attacks to redirect elsewhere or other javascript injection on hostile internet connections/captive WiFi portals.

Not a huge priority, but it seems like it could be trival to fix.

**Comment by JustAMan** [comment]
paging @joshuaboniface

**Comment by joshuaboniface** [comment]
@nvllsvm controls the jellyfin.media domain.

**Comment by anthonylavado** [comment]
>@nvllsvm controls the jellyfin.media domain.

@joshuaboniface there’s the other concern about the repo pages, but IIRC, you’ve said that’s a quirk of the setup, right?

**Comment by joshuaboniface** [comment]
I'm not sure I understand? https://jellyfin.org/downloads/ is the proper download page, and going to it non-secure should redirect to HTTPS.

**Comment by anthonylavado** [comment]
@joshuaboniface I just checked, if I go to http://jellyfin.org/downloads/, it does not automatically push me to the HTTPS page.

That said, if I do _click_ on a link, obviously they're all written as HTTPS, so that works. If I go to `repo` unsecured, that also pushes me to HTTPS.

**Comment by iotku** [comment]
The links on http://jellyfin.org/downloads/ direct to https repo as expected, but the point I was making is that if someone were to mitm they could change the link to a non-https link and continue modifying traffic (potentially to serve backdoored executables etc)

It's not a super likely scenario, but possible. Outside of hacking scenarios many ISPs like injecting javascript into non-https pages. 

Main point is that if I'm clicking on a https link I expect to remain on https. 

If I were to go to a http link intentionally I'm somewhat responsible for the potential risks involved there (especially if I'm on an insecure network).

**Comment by anthonylavado** [comment]
I managed to enable a setting that always enforces HTTPS. Closing as fixed.
